{
 "title": "Istio Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Requests / 5min",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 6, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(istio_requests_total[5m]))"
    }
   ]
  },
  {
   "title": "Requests / 30min By Destination App",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (destination_app) (rate(istio_requests_total[5m]))"
    }
   ]
  },
  {
   "title": "Requests / 5min By Source App",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (source_app) (rate(istio_requests_total[5m]))"
    }
   ]
  },
  {
   "title": "Bytes Sent / 5min By Destination App",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum by (destination_app) (rate(istio_request_bytes_sum[5m]))"
    }
   ]
  },
  {
   "title": "Bytes Sent / 5min By Source App",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "sum by (source_app) (rate(istio_request_bytes_sum[5m]))"
    }
   ]
  },
  {
   "title": "Distribution Of Response Codes",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 6, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (response_code) (rate(istio_requests_total[5m]))"
    }
   ]
  }
 ]
}