apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: allpass-ext-http
spec:
  hosts:
  - "*.com"
  ports:
  - number: 80
    name: http
    protocol: HTTP
  resolution: NONE
  location: MESH_EXTERNAL
---
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: allpass-ext-https
spec:
  hosts:
  - "*.com"
  ports:
  - number: 443
    name: https
    protocol: HTTPS
  resolution: NONE
  location: MESH_EXTERNAL
